Repository Payum/Payum, pull requests merged in 2021-03, with the labels that each got.

#887 Added helpful comments to get-it-started.md
  docs/paypal/rest/get-it-started.md
Labels: docs

#783 Use the CSPRNG provided by PHP 7
  src/Payum/Core/Security/Util/Random.php
Labels: enhancement

#888 Update alcohol/iso4217 which supports PHP8
  src/Payum/Core/composer.json
Labels: duplicate

#889 Replace basename for target url
  src/Payum/Core/Bridge/PlainPhp/Security/TokenFactory.php
  src/Payum/Core/Tests/Bridge/PlainPhp/Security/TokenFactoryTest.php
Labels: bug

#885 Migrate to Github actions
  .github/workflows/ci.yaml
  .travis.yml
Labels: integration

#891 Handle Paypal Rest gateway when using standard Payment object
  src/Payum/Paypal/Rest/Action/CaptureAction.php
  src/Payum/Paypal/Rest/Action/ConvertAction.php
  src/Payum/Paypal/Rest/Action/StatusAction.php
  src/Payum/Paypal/Rest/PaypalRestGatewayFactory.php
  src/Payum/Paypal/Rest/Tests/Action/CaptureActionTest.php
  src/Payum/Paypal/Rest/Tests/Action/ConvertActionTest.php
  src/Payum/Paypal/Rest/Tests/Action/StatusActionTest.php
Labels: bug, integration
