Repository Payum/Payum, pull requests merged in 2021-05, with the labels that each got.

#905 Add support for Laminas-db
  composer.json
  docs/frameworks-and-e-commerce-integration.md
  docs/payum-vs-omnipay.md
  docs/the-architecture.md
  src/Payum/Core/Bridge/Laminas/Storage/TableGatewayStorage.php
  src/Payum/Core/Bridge/Zend/Storage/TableGatewayStorage.php
  src/Payum/Core/CoreGatewayFactory.php
  src/Payum/Core/Tests/Bridge/Zend/Storage/TableGatewayStorageTest.php
  src/Payum/Core/composer.json
Labels: enhancement, integration

#904 Add roave/security-advisories
  composer.json
Labels: enhancement

#842 Add fields to set stripe variables for allow remember me and email
  src/Payum/Stripe/Resources/views/Action/obtain_checkout_token.html.twig
Labels: integration
