Repository Payum/Payum, pull requests merged in 2021-04, with the labels that each got.

#896 Handle cancel from PayPal rest action
  docs/paypal/rest/get-it-started.md
  src/Payum/Paypal/Rest/Action/CaptureAction.php
  src/Payum/Paypal/Rest/Action/StatusAction.php
  src/Payum/Paypal/Rest/Tests/Action/StatusActionTest.php
Labels: bug, integration

#827 Fix #824 Issue (Attempted to call an undefined method named "__toArray" of class "Stripe\Charge". Did you mean to call "toArray"?)
  src/Payum/Stripe/Action/Api/CreateChargeAction.php
Labels: bug, integration

#846 Add PaypalExpressCheckout refund
  src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/RefundTransactionAction.php
  src/Payum/Paypal/ExpressCheckout/Nvp/Api.php
  src/Payum/Paypal/ExpressCheckout/Nvp/PaypalExpressCheckoutGatewayFactory.php
  src/Payum/Paypal/ExpressCheckout/Nvp/Request/Api/RefundTransaction.php
  src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/Api/RefundTransactionActionTest.php
  src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Request/Api/RefundTransactionTest.php
Labels: enhancement, integration

#814 Updated Payex test url
  src/Payum/Payex/Api/AgreementApi.php
  src/Payum/Payex/Api/OrderApi.php
  src/Payum/Payex/Api/RecurringApi.php
Labels: bug, integration

#901 Add support for Symfony HttpClient
  src/Payum/Core/CoreGatewayFactory.php
Labels: enhancement, integration

#839 Upgrade to Stripe v7
  composer.json
  src/Payum/Stripe/Action/Api/CreateChargeAction.php
  src/Payum/Stripe/Action/Api/CreateCustomerAction.php
  src/Payum/Stripe/Action/Api/CreatePlanAction.php
  src/Payum/Stripe/Action/Api/CreateSubscriptionAction.php
  src/Payum/Stripe/Action/Api/CreateTokenAction.php
  src/Payum/Stripe/composer.json
Labels: enhancement, integration

#801 [Stripe][FIX] LogicException when card is declined
  src/Payum/Stripe/Extension/CreateCustomerExtension.php
  src/Payum/Stripe/Tests/Extension/CreateCustomerExtensionTest.php
Labels: bug
